### ISSUE TITLE
VM Failed to deploy

### ISSUE THREAD

**Issue by abfleishman** [Azure/AzureVM#11]
I am trying to create a VM with AzureVM on windows 10 and R 3.6.1 and I cannot seem to get it to work and the error messages are not very helpful. 

The error is "Unable to deploy template".  

I have tried different vm sizes and regions and configs.  Thoughts?

```
devtools::install_github("Azure/AzureVM")

library(AzureVM)
library(AzureRMR)
sub<-AzureRMR::create_azure_login()

sub<-AzureRMR::get_azure_login()$get_subscription_by_name("CMI_Azure")
hm<-sub$list_vm_sizes("westus2")
sub$create_vm(name="gpuusgs2", 
              user_config(username = "jimmy",
                          sshkey = "C:/Users/ConservationMetrics/.ssh/act-learn-key.pub"),
              size="Basic_A1",
              config="ubuntu_dsvm",
              location="westus2")
```

> Creating resource group 'gpuusgs2'
> Deploying template 'gpuusgs2'
> Waiting for provisioning to complete
> .....Error : 
> Unable to deploy template
> Deleting resource group 'gpuusgs2'. This operation may take some time to complete.
> Error: Unable to create VM

**Comment by hongooi73** [comment]
That error indicates the template deployment got halfway through, but one of the resources failed to be created. What you can do is create the resource group first, and then deploy the VM inside it. That way AzureVM won't delete the RG on failure and you can check the deployment result in the portal.

As a guess, I'd say to check that your ssh public key is valid.

**Comment by abfleishman** [comment]
I made a resource group ("test") and tried again and got this error
```
sub$create_vm(name="gpuusgs3",
              user_config(username = "cmi",
                          sshkey = "C:/Users/ConservationMetrics/.ssh/act-learn-key.pub"),
              size="Basic_A1",
              resource_group="test",
              config="ubuntu_18.04",
              location="westus2")
```
> Deploying template 'gpuusgs3'
> Waiting for provisioning to complete
> ....Error : 
> Unable to deploy template
> [1] "Error : \nUnable to deploy template\n"
> attr(,"class")
> [1] "try-error"
> attr(,"condition")
> <simpleError: 
> Unable to deploy template>

and it made these resources
![image](https://user-images.githubusercontent.com/9219852/66882930-109c2900-ef81-11e9-9ad0-d5f29a2a68c1.png)

Then I tried with a sshkey that was bad by editing it manually and immediately got this error

> Creating resource group 'gpuusgs4'
> Deploying template 'gpuusgs4'
> Error in process_response(res, match.arg(http_status_handler)) : 
>   Bad Request (HTTP 400). Failed to complete operation. Message:
> Deployment template validation failed: 'The provided value for the template parameter 'sshKeyData' at line '20' and column '31' is not
> valid.'.
> Deleting resource group 'gpuusgs4'. This operation may take some time to complete.
> Error: Unable to create VM

Any other ideas or info that I could provide to help you help me?  Thank you in advance!

**Comment by hongooi73** [comment]
That looks like all the resources were created except the VM. You can go to the resource group in the Azure portal and view the deployments; it should give you some more information.

You may have run into the [vCPU quota limit](https://docs.microsoft.com/en-au/azure/virtual-machines/windows/quotas) on your sub.

**Comment by abfleishman** [comment]
I have tons of quota left.  Looking into the failure message in the portal it seems that the default disk type is not compatible with the VM size I need.  Is there an easy way to specify the "storage account type Premium_LRS of disk" with `vm_create` ?

> Requested operation cannot be performed because the VM size Standard_D1_v2 does not support the storage account type Premium_LRS of disk ''. Consider updating the VM to a size that supports Premium storage.

**Comment by hongooi73** [comment]
At the moment, the disk type for the DSVM is fixed. (You can specify the disk type for any extra storage disks you add, but the DSVM comes with one storage disk by default which is set to Premium_LRS.)

You can set the VM size to Standard_DS1_v2 instead of D1_v2. List of VM sizes:

https://docs.microsoft.com/en-us/azure/virtual-machines/windows/sizes-general

**Comment by abfleishman** [comment]
I am actually needing to use Standard_NC6_Promo or Standard_NC6 (because of cost) and the need for a GPU enabled VM.  We can't afford the v2 or v3 VMs. Is there any way to adjust this or do I have to give up on using your package 😢?

**Comment by hongooi73** [comment]
I'll see what I can do. Note that AzureVM is really only useful if you're planning to deploy large numbers of VMs on a programmatic basis; if you're only deploying a few, it's probably easier just to use the portal.

**Comment by hongooi73** [comment]
Forgot to add: the other thing you can do is run `build_template_definition` and `build_template_parameters` to create the VM deployment json. You can then edit these before deploying them with AzureRMR's `resource_group$deploy_template()` method.
