### ISSUE TITLE
Error when try to use sub$get_vm function

### ISSUE THREAD

**Issue by MislavSag** [Azure/AzureVM#15]
I am trying to start my VM from R. I read several vignettes, but with no success. First I log in with:

`AzureRMR::create_azure_login()`

This opens tab in a web browser, it says I should go back to R. Than, in R I execute:

```
az <- AzureRMR::get_azure_login()
az$list_subscriptions()
```
This gives me the list of subscriptions (actually, I have only one).

Then I use get_subscription:
sub <- az$get_subscription('9a768f9f-xxxxxxxxxxxxxxxxxxx')

Now, if I try to 'get' VM (I tried both):

```
vm <- sub$get_vm('CT-VM-01')
vm <- sub$get_vm('CT-VM-01', 'Infrastructure')

```
I get errors:

> Error in process_response(res, match.arg(http_status_handler)) : 
>   Not Found (HTTP 404). Failed to complete operation. Message:
> ResourceGroupNotFound
> Resource group 'CT-VM-01' could not be found.
and:

> Error in process_response(res, match.arg(http_status_handler)) : 
>   Not Found (HTTP 404). Failed to complete operation. Message:
> DeploymentNotFound
> Deployment 'CT-VM-01' could not be found.

Please help: how can I connect to VM, start it and do some other operations.

**Comment by hongooi73** [comment]
The subscription method is for retrieving a VM that sits in its own resgroup. It's really meant to be the counterpart to the `create_vm` method for subscriptions, which will create a resgroup first and then create a VM inside it.

You can use this to retrieve an arbitrary VM, assuming you know the resgroup it's in:

```
sub$
    get_resource_group("resgroupname")$
    get_vm("CT-VM-01")
```

**Comment by MislavSag** [comment]
@Hong-Revo , I tried your code snippet, but it stil returns the error. Here is the code:
```
# createa Azure login
AzureR_dir()
AzureRMR::create_azure_login()

# start Azure Virtual Machine
az <- AzureRMR::get_azure_login()
az$list_subscriptions()
sub <- az$get_subscription('9a768f9f-735e-xxxxxxxxxxxxxxxxxxxxxxx')
vm <- sub$get_resource_group('Infrastructure')$get_vm('CT-VM-01')
```
The error is:

> Error in process_response(res, match.arg(http_status_handler)) : 
>   Not Found (HTTP 404). Failed to complete operation. Message:
> DeploymentNotFound
> Deployment 'CT-VM-01' could not be found.

**Comment by hongooi73** [comment]
See `?get_vm`. This method is for retrieving the _collection_ of resources that make up a VM (IP address, Vnet, security group, etc), ie, the template that deploys it. This requires that you have the template still present in the resgroup.

If all you want is the VM resource itself, use `get_vm_resource`.

**Comment by MislavSag** [comment]
It works with `get_vm_resource`! Thanks.
