### ISSUE TITLE
R Studio on Azure

### ISSUE THREAD

**Issue by Jimaras08** [Azure/AzureVM#22]
Hi there!

What is the best way of programmatically spinning up an R Studio environment on demand with specific dependencies, e.g. R version, CPU, packages, ... ?

Azure ML CI is a managed VM. Thus, you can't choose the R version you want. One may fire up another CI within R Studio for using a different R environments but that seems to decrease rapid experimentation.

Is DSVM as an unmanaged VM the way to go here? One may create DSVM environments via Azure CLI by using ARM (templates). Perhaps there is something that allows to specify the R version?

AzureVM seems to create DSVMs and provides the vm_config function which allows to specify the image to deploy.

Any other ideas?

Thank you!

**Comment by hongooi73** [comment]
Hi, bear in mind I'm not an architect.

I haven't used the DSVM for some time, but I believe it does include RStudio Server. It's just a regular VM that happens to have a bunch of software preloaded, so you're free to install your own version of R. Note that changing the R version would happen post-deployment, ie you login to the VM and install the software manually.

If you don't want to use the DSVM, you can choose any other Linux VM image. You'll just need to install all the tools you want to use, including R and RStudio Server. A vanilla Ubuntu image would be a good choice here.

Another alternative to RStudio is to use [VSCode Remoting](https://code.visualstudio.com/docs/remote/ssh) to talk to R in your Linux VM. I've done this, along with the [R extension](https://marketplace.visualstudio.com/items?itemName=Ikuyadeu.r) for VSCode, and it works great. The advantage here is you don't need to install RStudio on the VM, although obviously you do need to be using VSCode.

Alternatively you could spin up a Windows VM and install the RStudio standalone version. This would require connecting via RDP, as opposed to SSH or HTTP[S].

In all cases, you'll need to ensure you have enough CPU and storage to handle your workloads. Consult [the list on MS Docs](https://docs.microsoft.com/en-us/azure/virtual-machines/sizes) for more info.

**Comment by Jimaras08** [comment]
Thank you so much for you answer!

I was hoping that one can create a DSVM via create_vm (which is based on AzureRMR) and specify the underlying software (R Studio Server) by simply using a custom image via vm_config. Am I misunderstanding here something?

I think I get your point: in my case DIY with regular Azure VM and a proper image, eg with Ubuntu, R version and R Studio Server might be the better fit. I guess, the proper way of doing this programmatically is by using ARM since there isn't any SDK out yet. I actually thought that this here is already what I'm looking for ...

Re VS Code Remote, that's just access to the computer instance. Correct?

**Comment by hongooi73** [comment]
There's only one DSVM image supplied by Microsoft. What you can do is create a DSVM, modify it to your liking, and then save it as a custom image. You can then deploy more VMs based on your image, and they'll have the software that you want. This later deployment can be done either via AzureVM or in the portal.

If you're going to be tinkering a lot with the installed software, then starting with a vanilla image may be the best option, yes.

How VSCode remoting works is that you install VSCode plus the extension on your local machine, then tell it the address/DNS name of your VM. It then uses ssh to connect to the VM and handles everything from then on. The docs explain it quite well.
