### ISSUE TITLE
SSH key for VM login Store in KeyVault rather than Download option.

### ISSUE THREAD

**Issue by apoorvkapil** [Azure/AzureVM#23]
Hello Team,

I was trying to secure a **VM with SSH key** pairs. I found during VM creation in advance options i can create new KEYs as shown in below screenshot. However i was a bit surprised that rather than storing a keys in azure Key Vault by default, it was offering me to download it over the internet.
![image](https://user-images.githubusercontent.com/17564110/154507511-394951f1-ea5b-4c5c-baed-5fb0051521eb.png)

This been a bit against the security standard, because a key is assumed to be secure if it never been exchanged over the internet.

I wanted to check if there any development going on to secure this or any backlog to make it work by default with azure managed bastion host while storing the keys on Key Vault.

**Comment by hongooi73** [comment]
This repo is for AzureVM, an R package for interacting with the VM service. It has nothing to do with the Azure portal, or with the VM team. Contact your local MS rep if you have an issue.
